### PR TITLE
Compatibility with Rails 4.1

### PR DESCRIPTION
**Pull request by pschambacher**
cc @grosser @osheroff 

Get a failing test [there](https://github.com/zendesk/active_record_inherit_assoc/blob/pschambacher/rails4/test/test_inherit_assoc.rb#L69) with Rails 4.2 so I'll deal with it later.

### CODE REVIEW

**Comment by osheroff** [comment]
:+1:

**Comment by grosser** [comment]
:+1:

**Comment by pschambacher** [comment]
```
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.
```

:facepunch: :boom: :sob:

**Comment by grosser** [comment]
now you do :)

On Thu, Feb 5, 2015 at 8:55 AM, Pierre Schambacher <notifications@github.com

**Comment by pschambacher** [comment]
It's happening

Gem released, thanks :)

**Pull request merged**
